apiVersion: v1
kind: Secret
metadata:
  name: kagikanri-secrets
  namespace: kagikanri
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  # Generate with: echo -n "your-token" | base64
  git-token: <base64-encoded-git-token>
  
  # Generate database encryption key with: openssl rand -hex 32 | base64
  db-encryption-key: <base64-encoded-32-byte-key>

---
apiVersion: v1
kind: Secret
metadata:
  name: kagikanri-gpg-key
  namespace: kagikanri
type: Opaque
data:
  # GPG private key for pass encryption
  # Export with: gpg --export-secret-keys <key-id> | base64
  gpg-private-key: <base64-encoded-gpg-private-key>
  
  # GPG key ID
  gpg-key-id: <base64-encoded-key-id>